name: build

on:
  push:
    branches: [main]     # or whatever branch triggers your build

jobs:
  inject-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Replace the placeholder with the secret
      - name: Inject API_KEY into HTML
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Create a clean build dir
          mkdir -p dist
          # Replace the marker in the template (-i = in-place)
          sed "s|__REPLACE_API_KEY__|$API_KEY|g" index.template.html > dist/index.html

      # 3. Commit or deploy the **built** file, not the template
      # Here we commit back to main just so you can see the result; swap for
      # your deploy step (e.g. gh-pages, Netlify, Vercel) in real projects.
      - name: Push built artifact back to repo
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv dist/index.html .
          git add index.html
          git commit -m "🤖 Injected secrets on $(date -u '+%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push origin HEAD:main
